name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  steps:
    - name: Copy repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Prettier
      run: npm run prettier:check

    - name: Test
      run: npm run test

    - name: Test E2E
      run: npm run test:e2e

    - name: Build
      run: npm run build
